[workspace]
members = [
    "indexing/columnar",
    "indexing/columnar_codegen/codegen",
    "indexing/columnar_codegen/macros",
    "indexing/columnar_codegen/builder",
    "indexing/toolkit/", "indexing/thirdparty",
]
resolver = "3"
