[package]
name = "toolkit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
serde_json = "1.0.96"
num = "0.4.0"
serde = { version = "1.0.164", features = ["derive"] }
roaring = "0.11.2"
num-traits = "0.2.19"
